core/urls.py
from django.urls import path
from core.views import (
    HomeView,
    FollowDoneView,
    UnfollowDoneView,
    PostCreatView,
    PostDeleteView,
    PostDetailView,
    PostLikeView,
    PostUnlikeView,
    PostCommentView,
    PostSaveView,
    PostUnsaveView,
    LikedPostsView,
    ExplorePostsView,
    SavedPostsView,
    )
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('feed/', login_required(HomeView.as_view()), name='home_feed_view'),

    # follow and unfollow view
    path('follow/done/', login_required(FollowDoneView.as_view()), name='follow_done_view'),
    path('unfollow/done/', login_required(UnfollowDoneView.as_view()), name='unfollow_done_view'),

    # post related urls
    path('post/<int:id>/', login_required(PostDetailView.as_view()), name='post_detail_view'),
    path('post/create/', login_required(PostCreatView.as_view()), name='post_create_view'),
    path('post/delete/<int:id>/', login_required(PostDeleteView.as_view()), name='post_delete_view'),
    path('post/save/<int:id>/', login_required(PostSaveView.as_view()), name='post_save_view'),
    path('post/unsave/<int:id>/', login_required(PostUnsaveView.as_view()), name='post_unsave_view'),
    
    path('post/liked/', login_required(LikedPostsView.as_view()), name='liked_posts_view'),
    path('post/saved/', login_required(SavedPostsView.as_view()), name='saved_posts_view'),
    path('post/explore/', login_required(ExplorePostsView.as_view()), name='explore_posts_view'),

    path('post/like/<int:id>/', PostLikeView.as_view(), name='post_like_view'),
    path('post/unlike/<int:id>/', PostUnlikeView.as_view(), name='post_unlike_view'),
    path('post/comment/<int:id>/', PostCommentView.as_view(), name='post_comment_view'),
]

insta_becky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    path('', include('user.urls')),
]

urlpatterns.extend(
    static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
        )
    )

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from cloudinary.models import CloudinaryField


from core.utils import auto_save_current_user
# Create your models here.

User = get_user_model()


# Posts Model
class Post(models.Model):
    # id = models.AutoField(primary_key=True)     # generated by default 
    text = models.CharField(max_length=140, blank=True, null=True)  # null == None, blank = ''
    # image = models.ImageField(upload_to='post_images')   # BASE_DIR -> media -> post_images
    image = CloudinaryField('post_images')
    user = models.ForeignKey(User, on_delete=models.PROTECT, editable=False)    # user_id
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Post, self).save(*args, **kwargs)

    @property
    def likes_count(self):
        count = self.like_set.count()
        return count

    @property
    def comments_count(self):
        count = self.comment_set.count()
        return count


# Comments Model
class Comment(models.Model):
    text = models.CharField(max_length=240)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    commented_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Comment, self).save(*args, **kwargs)

# Likes Model
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    liked_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.id)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Like, self).save(*args, **kwargs)

# Followers Model
class Follow(models.Model):
    user = models.ForeignKey(User, related_name='follow_follower', on_delete=models.CASCADE, editable=False)
    followed = models.ForeignKey(User, related_name='follow_followed', on_delete=models.CASCADE)
    followed_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user} --> {self.followed}"

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Follow, self).save(*args, **kwargs)


class SavedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    saved_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post.pk)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(SavedPost, self).save(*args, **kwargs)

core/forms.py
from django import forms
from core.models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'image')
        widgets = {
            'text': forms.TextInput(attrs={
                    'class': 'form-control form-control-sm',
                    'placeholder': 'Caption this...'
                }
            )
        }

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.contrib.auth import get_user_model
from django.db.models import Count

from core.models import (
    Follow, 
    Post, 
    Like, 
    Comment, 
    SavedPost
    )
from core.forms import PostCreateForm

User = get_user_model()
# Create your views here.
class HomeView(View):
    template_name = 'core/feed.html'
    form_class = PostCreateForm

    def get(self, request, *arga, **kwargs):
        form = self.form_class()
        all_posts = Post.objects.all()
        context = { 'form': form, 'all_posts': all_posts }
        return render(request, self.template_name, context=context)


class PostDetailView(View):
    template_name = 'core/post_detail.html'

    def get(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            post_obj = Post.objects.get(pk=post_id)
        except Exception as e:
            return redirect(request.META.get('HTTP_REFERER'))

        try:
            Like.objects.get(user=request.user, post_id=post_id)
            liked_this_post = True
        except Exception as e:
            liked_this_post = False

        try:
            SavedPost.objects.get(user=request.user, post_id=post_id)
            post_saved = True
        except Exception as e:
            post_saved = False

        context = {
            'post': post_obj, 
            'liked_this_post': liked_this_post, 
            'post_saved': post_saved,
            }
            
        return render(request, self.template_name, context=context)


class PostCreatView(View):
    template_name = 'core/feed.html'
    form_class = PostCreateForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('home_feed_view')
        else:
            context = { 'form': form }
            return render(request, self.template_name, context=context)


class PostDeleteView(View):

    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        try:
            post_obj = Post.objects.get(pk=post_id)
        except Exception as e:
            pass

        if request.user == post_obj.user:
            post_obj.delete()

        return redirect(request.META.get('HTTP_REFERER'))


class PostSaveView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        
        try:
            post_obj = Post.objects.get(pk=post_id)
        except Exception as e:
            pass

        try:
            SavedPost.objects.create(post_id=post_id)
        except Exception as e:
            pass        

        return redirect(request.META.get('HTTP_REFERER'))


class PostUnsaveView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        
        try:
            savedpost_obj = SavedPost.objects.get(post_id=post_id)
            savedpost_obj.delete()
        except Exception as e:
            pass       

        return redirect(request.META.get('HTTP_REFERER'))


class PostLikeView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            Like.objects.get(user=request.user, post_id=post_id)
        except Exception as e:
            Like.objects.create(post_id=post_id)

        return redirect(request.META.get('HTTP_REFERER'))


class PostUnlikeView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')

        try:
            like_obj = Like.objects.get(user=request.user, post_id=post_id)
            like_obj.delete()
        except Exception as e:
            pass

        return redirect(request.META.get('HTTP_REFERER'))


class PostCommentView(View):
    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('id')
        comment_text = request.POST.get('comment_text')
        
        Comment.objects.create(post_id=post_id, text=comment_text)

        return redirect(request.META.get('HTTP_REFERER'))


class FollowDoneView(View):
    def post(self, request, *args, **kwargs):
        followed_user_id = request.POST.get('followed_user_id')
        followed_user_obj = User.objects.get(pk=followed_user_id)

        try:
            Follow.objects.get(user=request.user, followed=followed_user_obj)
        except Exception as e:
            follow_obj = Follow.objects.create(followed=followed_user_obj)

        return redirect(request.META.get('HTTP_REFERER'))


class UnfollowDoneView(View):
    def post(self, request, *args, **kwargs):
        unfollowed_user_id = request.POST.get('unfollowed_user_id')
        unfollowed_user_obj = User.objects.get(pk=unfollowed_user_id)

        try:
            follow_obj = Follow.objects.get(user=request.user, followed=unfollowed_user_obj)
            follow_obj.delete()
        except Exception as e:
            pass

        return redirect(request.META.get('HTTP_REFERER'))


class LikedPostsView(View):
    template_name = 'core/liked_posts.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class SavedPostsView(View):
    template_name = 'core/saved_posts.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class ExplorePostsView(View):
    template_name = 'core/posts_explore.html'
    def get(self, request, *args, **kwargs):

        all_posts = Post.objects.annotate(count=Count('like')).order_by('-count')
        context = {'all_posts': all_posts}
        return render(request, self.template_name, context=context)

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'styles/core/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/core/navbar.css' %}">
    {% block extra_head %}{% endblock %}

    <title>Insta Clone</title>
  </head>
  <body style="background-color: #fafafa;">

    {% include 'components/navbar.html' %}

    <section>
      {% block content %}{% endblock %}
    </section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

   
    <style>
      .github-corner > svg {
        fill: #000;
        right: 0;
        top: 0;
        transform: scale(1, 1);
        position: fixed;
      }
    </style>

  </body>
</html>

templates/core/feed.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/core/post_card.css' %}">
{% endblock %}

{% block content %}

    <!-- Messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success w-50 mt-4 mx-auto text-center {{ message.tags }}" role="alert" style="font-size: 13px;">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12 col-md-8">
                <div class="card mx-auto mb-4" style="max-width: 32rem;">
                    <div class="card-body">
                        <div>

                            <!-- Post Create Form -->
                            <form method="POST" action="{% url 'post_create_view' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="mb-2">{{ field }}</div>
                                {% endfor %}
                                <button class="btn btn-sm btn-primary" type="submit">Save</button>
                            </form>
                            <!-- Post Create Form End -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8">

                <!-- All the posts in database -->
                {% for post in all_posts %}

                    <!-- Single Posts Card -->
                    {% include 'components/post_card.html' %}
                    
                {% endfor %}
                <!-- All the posts in database -->

            </div>
        </div>
    </div>
{% endblock %}

templates/core/liked_posts.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All Liked Posts -->
            {% for like_obj in request.user.like_set.all %}
                {% with post=like_obj.post %}

                <!-- Single Posts Grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post Image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">

                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- total comments -->
                                {{ post.comments_count }}
                                
                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single Posts Grid end -->

                {% endwith %}
            {% endfor %}
            <!-- All Liked Posts end -->

        </div>
    </div>

{% endblock %}

templates/core/post_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/core/post_card.css' %}">
{% endblock %}

{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-12">

                <!-- Single Posts in Detail Card -->
                {% include 'components/post_detail_card.html' %}
                
            </div>
        </div>
    </div>

{% endblock %}

templates/core/posts_explore.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All posts ordered by number of likes -->
            {% for post in all_posts %}
                <!-- Single post grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post Image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">

                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- Total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- Total comments -->
                                {{ post.comments_count }}

                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single post grid end -->

            {% endfor %}
            <!-- All posts ordered by number of likes end -->

        </div>
    </div>

{% endblock %}

templates/core/saved_posts.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

    <div class="container my-5">
        <div class="row justify-content-center">

            <!-- All Saved Posts -->
            {% for savedpost_obj in request.user.savedpost_set.all %}
                {% with post=savedpost_obj.post %}

                <!-- Single Posts Grid -->
                <div class='col-12 col-md-4 col-lg-3 my-4 mx-3 px-0 card'>
                    <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                        <!-- Post image -->
                        <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">
                        
                        <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                            <span class="mx-2">
                                <span class="far fa-heart"></span>

                                <!-- Total likes -->
                                {{ post.likes_count }}

                            </span> 
                            <span class="mx-2">
                                <span class="far fa-comment"></span>

                                <!-- Total comments -->
                                {{ post.comments_count }}

                            </span>
                        </div>
                    </a>
                </div>
                <!-- Single Posts Grid end -->

                {% endwith %}
            {% endfor %}
            <!-- All Saved Posts end -->

        </div>
    </div>

{% endblock %}