authentication/urls.py
from django.urls import path
from authentication.views import (
    SignInView,
    SignUpView, 
    SignOutView,
    PRView, PRDone, PRConfirm, PRComplete,
    PWDChangeView, PWDChangeDoneView,
    )
from django.urls import reverse_lazy


from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
    )


urlpatterns = [
    path('',  SignInView.as_view(), name='signin_view'),
    path('signup/',  SignUpView.as_view(), name='signup_view'),
    path('signout/',  SignOutView.as_view(), name='signout_view'),
    
    
    path('password/reset/', 
        PasswordResetView.as_view(
            email_template_name = 'authentication/password_reset_email.html',
            template_name = 'authentication/password_reset.html',
        ), 
        name='password_reset'),
    
    path('password/reset/done/',  
        PasswordResetDoneView.as_view(
            template_name = 'authentication/password_reset_done.html'
        ) ,
        name='password_reset_done'),

    path('password/reset/confirm/<uidb64>/<token>', 
        PasswordResetConfirmView.as_view(
            template_name = 'authentication/password_reset_confirm.html'
        ) , 
        name='password_reset_confirm'),

    path('password/reset/complete/', 
        PasswordResetCompleteView.as_view(
            template_name = 'authentication/password_reset_complete.html'
        ) , 
        name='password_reset_complete'),

    
    path(
        'password/change/', 
        PasswordChangeView.as_view(
            template_name = 'authentication/password_change.html',
            success_url = reverse_lazy('password_change_done_view')
            ), 
        name='password_change_view'
        ),
    path(
        'password/change/done/', 
        PasswordResetDoneView.as_view(
            template_name = 'authentication/password_change_done.html'
            ), 
        name='password_change_done_view'
        )
]

core/urls.py
from django.urls import path
from core.views import (
    HomeView,
    FollowDoneView,
    UnfollowDoneView,
    PostCreatView,
    PostDeleteView,
    PostDetailView,
    PostLikeView,
    PostUnlikeView,
    PostCommentView,
    PostSaveView,
    PostUnsaveView,
    LikedPostsView,
    ExplorePostsView,
    SavedPostsView,
    )
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('feed/', login_required(HomeView.as_view()), name='home_feed_view'),

    # follow and unfollow view
    path('follow/done/', login_required(FollowDoneView.as_view()), name='follow_done_view'),
    path('unfollow/done/', login_required(UnfollowDoneView.as_view()), name='unfollow_done_view'),

    # post related urls
    path('post/<int:id>/', login_required(PostDetailView.as_view()), name='post_detail_view'),
    path('post/create/', login_required(PostCreatView.as_view()), name='post_create_view'),
    path('post/delete/<int:id>/', login_required(PostDeleteView.as_view()), name='post_delete_view'),
    path('post/save/<int:id>/', login_required(PostSaveView.as_view()), name='post_save_view'),
    path('post/unsave/<int:id>/', login_required(PostUnsaveView.as_view()), name='post_unsave_view'),
    
    path('post/liked/', login_required(LikedPostsView.as_view()), name='liked_posts_view'),
    path('post/saved/', login_required(SavedPostsView.as_view()), name='saved_posts_view'),
    path('post/explore/', login_required(ExplorePostsView.as_view()), name='explore_posts_view'),

    path('post/like/<int:id>/', PostLikeView.as_view(), name='post_like_view'),
    path('post/unlike/<int:id>/', PostUnlikeView.as_view(), name='post_unlike_view'),
    path('post/comment/<int:id>/', PostCommentView.as_view(), name='post_comment_view'),
]

insta_becky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    path('', include('user.urls')),
]

urlpatterns.extend(
    static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
        )
    )

authentication/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.managers import CustomUserManager
from cloudinary.models import CloudinaryField

# Create your models here.


GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('None', 'Prefer not to say.'),
]


class User(AbstractUser):
    # picture = models.ImageField(upload_to='profile_pictures', null=True, blank=True)
    picture = CloudinaryField('profile_pictures')
    full_name = models.CharField(max_length=100, help_text='Help people discover your account by using the name you\'re known by: either your full name, nickname, or business name.')
    email = models.EmailField(unique=True)

    # Optional fields
    bio = models.TextField(null=True, blank=True, help_text='Provide your personal information, even if the account is used for a business, a pet or something else. This won\'t be a part of your public profile.')
    website = models.URLField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    is_private_account = models.BooleanField(default=False)

    first_name = None
    last_name = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name','username',]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    @property
    def follower_count(self):
        count = self.follow_followed.count()
        return count

    @property
    def following_count(self):
        count = self.follow_follower.count()
        return count

    @property
    def posts_count(self):
        count = self.post_set.count()
        return count

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class UserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name', 'email', 'username', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name', 'email', 'username',)

authentication/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib import messages
from django.http import HttpResponse
from django.urls import reverse_lazy
from authentication.forms import UserForm
from django.contrib.auth import (
    authenticate, 
    login, logout, 
    get_user_model,
    )
from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
    )
# Create your views here.

User = get_user_model()

class SignInView(View):
    template_name = 'authentication/signin.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home_feed_view')
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email_username = request.POST.get('email_username')
        password = request.POST.get('password')

        try:
            user_obj = User.objects.get(username=email_username)
            email = user_obj.email
        except Exception as e:
            email = email_username

        user = authenticate(request, email=email, password=password)
        
        if user is None:
            messages.error(request, 'Invalid Login.', extra_tags="error")
            return render(request, self.template_name) 

        login(request, user)
        messages.success(request, 'Thanks for Login, Welcome to Insta Clone.', extra_tags='success')
        return redirect('home_feed_view')
        


class SignUpView(View):
    template_name = 'authentication/signup.html'
    form_class = UserForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home_feed_view')
        
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('signin_view')

        context = {'form': form}

        return render(request, self.template_name, context)


class SignOutView(View):
    def post(self, request, *args, **kwargs):
        # is user is not authenticated
        logout(request)
        return redirect('signin_view')


class PRView(PasswordResetView):
    email_template_name = 'authentication/password_reset_email.html'
    template_name = 'authentication/password_reset.html'

class PRDone(PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html'

class PRConfirm(PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'

class PRComplete(PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'


class PWDChangeView(PasswordChangeView):
    template_name = 'authentication/password_change.html'
    success_url = reverse_lazy('password_change_done_view')

class PWDChangeDoneView(PasswordChangeDoneView):
    template_name = 'authentication/password_change_done.html'

templates/authentication/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra_head %}{% endblock %}

    <title>Insta Clone</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

   
    <style>
      .github-corner > svg {
        fill: #000;
        right: 0;
        top: 0;
        transform: scale(1, 1);
        position: fixed;
      }
    </style>

  </body>
</html>

templates/authentication/password_change.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_change.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 my-4">
                <div class="card password__change__card m-auto">
                    <div class="card-header">
                        <p class="m-0" style="color: #5f5f5f;">Change Password</p>
                    </div>
                    <div class="card-body offset-md-2">
                        <form method="POST">
                            {% csrf_token %}

                            <!-- Password Change Form -->
                            {% for field in form %}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label col-form-label-sm text-md-right font-weight-bolder" for="{{ field.auto_id }}">
                                        {{ field.label }}
                                    </label>
                                    <div class="col-sm-8">
                                        {{ field }}
                                        <small id="passwordHelpBlock" class="form-text text-muted">
                                            {{ field.help_text }}
                                        </small>
                                        <div class="{% if field.errors %}validation__error{% else %}invalid-feedback{% endif %}">
                                            {{ field.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <!-- End Password Change Form -->

                            <div class="offset-md-2 my-1">
                                <button class="btn btn-sm btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/authentication/password_change_done.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_change.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 my-4">
                <div class="card password__change__card m-auto">
                    <div class="text-center p-5">

                        <!-- Password Changed Success Message -->
                        <p class="text-muted">Congratulations, your password has been successfully changed. 
                            <a href="{% url 'profile_view' request.user.username %}">Go Back to Profile</a>
                        </p>
                        <!-- End Password Changed Success Message -->

                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/authentication/password_reset.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/instalogo.png' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav>
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" required maxlength="240" autocomplete="email">
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn">Send Signin Link</button>
                            </div>
                        </form>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_complete.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Successfully Reset</h4></div>
                    <div class="forgot__password__text py-2">
                        You can go ahead and signin now.
                        <br>
                        <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">
                            Click here to Sign In.
                        </a>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_confirm.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        {% if form %}
                            <div>
                                {% if form.non_field_errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ form.non_field_errors }}
                                    </div>
                                {% endif%}
                            </div>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" placeholder="Password">
                                    <p>{{ form.new_password1.errors }}</p>
                                </div>
                                <div class="my-1 form__input">
                                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" placeholder="Retype Password">
                                    <p>{{ form.new_password2.errors }}</p>
                                </div>
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Set Password</button>
                                </div>
                            </form>
                        {% else %}
                            <div class="py-2">
                                <strong style="color: #ff6600;">Your password reset link is invalid or expired.</strong>
                            </div>
                        {% endif %}
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_done.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_reset.css' %}">
{% endblock %}

{% block content %}

{% include 'authentication/components/no_login_navbar.html' %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mx-auto mt-4 mb-5">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Email Sent.</h4></div>
                    <div class="forgot__password__text py-2">
                        Check your registered email for the Password Reset link.
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/authentication/password_reset_email.html
Devjunction is trying to steal your pasword- {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/signup.css' %}">
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto signup__card">
                <img src="{% static 'img/instalogo.png' %}" class="insta__logo mt-4 mb-3 mx-auto">
                <div class="signup">
                    <p class="signup__card__text">Sign up to see photos and videos from your friends.</p>
                    <div class="my-4 mx-auto text-center">
                        <button class="btn btn-sm auth__btn">Log in with Facebook</button>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div>
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif%}
                    </div>
                    <div class="signup__form mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_username" type="text" name="username" placeholder="Username" class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.username.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_full_name" type="text" name="full_name" placeholder="Full Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.full_name.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control {% if form.password1s.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password1.errors }}
                                </div>
                            </div>
                            <div class="my-1 form__input">
                                <input id="id_password2" type="password" name="password2" placeholder="Retype Password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                <div class="invalid-feedback">
                                    {{ form.password2.errors }}
                                </div>
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn" type="submit">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <p class="terms__conditions mb-4">By signing up, you agree to our <strong>Terms</strong> , <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .</p>
                </div>
            </div>
            <div class="text-center card mt-2 px-5 mx-auto signup__card">
                <p class="have__an__account py-3">Have an account? <a href="{% url 'signin_view' %}" class="text-decoration-none">Sign in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}